pipeline:
  name: Deploy Demo
  identifier: Deploy_Demo
  projectIdentifier: harness_Demo
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: DeployK8s
        identifier: DeployK8s
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: K8Service
          environment:
            environmentRef: Production
            deployToAll: false
            infrastructureDefinitions:
              - identifier: Infra
          execution:
            steps:
              - step:
                  type: K8sRollingDeploy
                  name: K8sRollingDeploy_1
                  identifier: K8sRollingDeploy_1
                  spec:
                    skipDryRun: true
                    pruningEnabled: false
                    delegateSelectors:
                      - helm-delegate
                  timeout: 10m
            rollbackSteps:
              - step:
                  name: Swap primary with stage service
                  identifier: rollbackBgSwapServices
                  type: K8sBGSwapServices
                  timeout: 10m
                  spec:
                    skipDryRun: false
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
        delegateSelectors:
          - helm-delegate
        when:
          pipelineStatus: All
  properties:
    ci:
      codebase:
        connectorRef: org.GitHUBConn
        repoName: harness_Demo
        build: <+input>
  delegateSelectors:
    - helm-delegate
