pipeline:
  name: Deploy Demo
  identifier: Deploy_Demo
  projectIdentifier: harness_Demo
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: DeployK8s
        identifier: DeployK8s
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: K8Service
          environment:
            environmentRef: Production
            deployToAll: false
            infrastructureDefinitions:
              - identifier: Infra
          execution:
            steps:
              - step:
                  type: K8sBlueGreenDeploy
                  name: K8sBlueGreenDeploy_1
                  identifier: K8sBlueGreenDeploy_1
                  spec:
                    skipDryRun: true
                    pruningEnabled: false
                    skipUnchangedManifest: true
                    delegateSelectors:
                      - helm-delegate
                  timeout: 10m
                  failureStrategies:
                    - onFailure:
                        errors:
                          - Authentication
                        action:
                          type: Ignore
                  when:
                    stageStatus: Success
            rollbackSteps:
              - step:
                  name: Swap primary with stage service
                  identifier: rollbackBgSwapServices
                  type: K8sBGSwapServices
                  timeout: 10m
                  spec:
                    skipDryRun: false
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
